# Generated by Django 6.0.7 on 2026-08-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0004_appointment_email_appointment_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='team/')),
                ('description', models.TextField()),
            ],
        ),
    ]
